project:
  type: website

website:
  title: "Prompt Engineering"
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Modules"
        contents:
          - Module1.qmd
          - Module2.qmd
          - Module3.qmd
          - Module4.qmd
          - Module5.qmd
          - Module6.qmd
          - Module7.qmd
          - Module8.qmd
          - Module9.qmd
          - Module10.qmd
          - Module11.qmd
          - Module12.qmd
          - Module13.qmd
  
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true
