project:
  type: website

website:
  title: "Prompt Engineering"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Module 1
        file: Module1.qmd
      - text: Module 2
        file: Module2.qmd
      - text: Module 3
        file: Module3.qmd

format:
  html:
    toc: true
    theme: cosmo
