project:
  type: website

website:
  title: "Prompt Engineering"
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Modules"
        contents:
          - Module1.qmd
          - Module2.qmd
          - Module3.qmd
  
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true
